-- Atlántida
INSERT INTO Municipio (id_departamento, municipio) VALUES (1, 'La Ceiba')
INSERT INTO Municipio (id_departamento, municipio) VALUES (1, 'Tela')
INSERT INTO Municipio (id_departamento, municipio) VALUES (1, 'Jutiapa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (1, 'La Masica')
INSERT INTO Municipio (id_departamento, municipio) VALUES (1, 'Arizona')
INSERT INTO Municipio (id_departamento, municipio) VALUES (1, 'Esparta')
INSERT INTO Municipio (id_departamento, municipio) VALUES (1, 'San Francisco')
INSERT INTO Municipio (id_departamento, municipio) VALUES (1, 'Sonaguera')
GO

-- Choluteca
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'Choluteca')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'Apacilagua')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'Concepción de María')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'Duyure')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'El Corpus')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'El Triunfo')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'Marcovia')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'Morolica')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'Namasigüe')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'Orocuina')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'Pespire')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'San Antonio de Flores')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'San Isidro')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'San José')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'San Marcos de Colón')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'Santa Ana de Yusguare')
GO

-- Colón
INSERT INTO Municipio (id_departamento, municipio) VALUES (3, 'Trujillo')
INSERT INTO Municipio (id_departamento, municipio) VALUES (3, 'Balfate')
INSERT INTO Municipio (id_departamento, municipio) VALUES (3, 'Iriona')
INSERT INTO Municipio (id_departamento, municipio) VALUES (3, 'Limón')
INSERT INTO Municipio (id_departamento, municipio) VALUES (3, 'Sabá')
INSERT INTO Municipio (id_departamento, municipio) VALUES (3, 'Santa Fe')
INSERT INTO Municipio (id_departamento, municipio) VALUES (3, 'Santa Rosa de Aguán')
INSERT INTO Municipio (id_departamento, municipio) VALUES (3, 'Sonaguera')
INSERT INTO Municipio (id_departamento, municipio) VALUES (3, 'Tocoa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (3, 'Bonito Oriental')
GO

-- Comayagua
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'Comayagua')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'Ajuterique')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'El Rosario')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'Esquías')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'Humuya')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'La Libertad')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'Lamaní')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'La Trinidad')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'Lejamaní')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'Meámbar')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'Minas de Oro')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'Ojos de Agua')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'San Jerónimo')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'San José de Comayagua')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'San José del Potrero')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'San Luis')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'San Sebastián')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'Siguatepeque')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'Villa de San Antonio')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'Las Lajas')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'Taulabé')
GO

-- Copán
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'Santa Rosa de Copán')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'Cabañas')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'Concepción')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'Copán Ruinas')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'Corquín')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'Cucuyagua')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'Dolores')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'Dulce Nombre')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'El Paraíso')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'Florida')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'La Jigua')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'La Unión')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'Nueva Arcadia')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'San Agustín')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'San Antonio')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'San Jerónimo')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'San José')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'San Juan de Opoa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'San Nicolás')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'San Pedro')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'Santa Rita')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'Trinidad de Copán')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'Veracruz')
GO

-- Cortés
INSERT INTO Municipio (id_departamento, municipio) VALUES (6, 'San Pedro Sula')
INSERT INTO Municipio (id_departamento, municipio) VALUES (6, 'Choloma')
INSERT INTO Municipio (id_departamento, municipio) VALUES (6, 'Omoa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (6, 'Pimienta')
INSERT INTO Municipio (id_departamento, municipio) VALUES (6, 'Potrerillos')
INSERT INTO Municipio (id_departamento, municipio) VALUES (6, 'Puerto Cortés')
INSERT INTO Municipio (id_departamento, municipio) VALUES (6, 'San Antonio de Cortés')
INSERT INTO Municipio (id_departamento, municipio) VALUES (6, 'San Francisco de Yojoa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (6, 'San Manuel')
INSERT INTO Municipio (id_departamento, municipio) VALUES (6, 'Santa Cruz de Yojoa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (6, 'Villanueva')
INSERT INTO Municipio (id_departamento, municipio) VALUES (6, 'La Lima')
GO

-- El Paraíso
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Yuscarán')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Alauca')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Danlí')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'El Paraíso')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Güinope')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Jacaleapa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Liure')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Morocelí')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Oropolí')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Potrerillos')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'San Antonio de Flores')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'San Lucas')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'San Matías')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Soledad')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Teupasenti')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Texiguat')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Vado Ancho')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Yauyupe')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Trojes')
GO

-- Francisco Morazán
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Tegucigalpa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Alubarén')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Cedros')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Curarén')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'El Porvenir')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Guaimaca')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'La Libertad')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'La Venta')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Lepaterique')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Maraita')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Marale')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Nueva Armenia')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Ojojona')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Orica')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Reitoca')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Sabanagrande')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'San Antonio de Oriente')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'San Buenaventura')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'San Ignacio')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'San Juan de Flores')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'San Miguelito')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Santa Ana')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Santa Lucía')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Talanga')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Tatumbla')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Valle de Ángeles')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Villa de San Francisco')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Vallecillo')
GO

-- Gracias a Dios
INSERT INTO Municipio (id_departamento, municipio) VALUES (9, 'Puerto Lempira')
INSERT INTO Municipio (id_departamento, municipio) VALUES (9, 'Brus Laguna')
INSERT INTO Municipio (id_departamento, municipio) VALUES (9, 'Ahuas')
INSERT INTO Municipio (id_departamento, municipio) VALUES (9, 'Juan Francisco Bulnes')
INSERT INTO Municipio (id_departamento, municipio) VALUES (9, 'Ramón Villeda Morales')
INSERT INTO Municipio (id_departamento, municipio) VALUES (9, 'Wampusirpi')
GO

-- Intibucá
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'La Esperanza')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'Camasca')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'Colomoncagua')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'Concepción')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'Dolores')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'Intibucá')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'Jesús de Otoro')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'Magdalena')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'Masaguara')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'San Antonio')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'San Isidro')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'San Juan')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'San Marcos de la Sierra')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'San Miguel Guancapla')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'Santa Lucía')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'Yamaranguila')
GO

-- Islas de la Bahía
INSERT INTO Municipio (id_departamento, municipio) VALUES (11, 'Roatán')
INSERT INTO Municipio (id_departamento, municipio) VALUES (11, 'Guanaja')
INSERT INTO Municipio (id_departamento, municipio) VALUES (11, 'José Santos Guardiola')
INSERT INTO Municipio (id_departamento, municipio) VALUES (11, 'Utila')
GO

-- La Paz
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'La Paz')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'Aguanqueterique')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'Cabañas')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'Cane')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'Chinacla')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'Guajiquiro')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'Lauterique')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'Marcala')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'Mercedes de Oriente')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'Opatoro')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'San Antonio del Norte')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'San José')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'San Juan')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'San Pedro de Tutule')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'Santa Ana')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'Santa Elena')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'Santa María')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'Santiago de Puringla')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'Yarula')
GO

-- Lempira
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Gracias')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Belén')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Candelaria')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Cololaca')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Erandique')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Gualcince')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Guarita')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'La Campa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'La Iguala')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Las Flores')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'La Unión')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'La Virtud')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Lepaera')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Mapulaca')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Piraera')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'San Andrés')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'San Francisco')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'San Juan Guarita')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'San Manuel Colohete')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'San Marcos de Caiquín')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'San Rafael')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'San Sebastián')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Santa Cruz')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Talgua')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Tambla')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Tomalá')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Valladolid')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Virginia')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'San Marcos de Ocotepeque')
GO

-- Ocotepeque
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'Nueva Ocotepeque')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'Belén Gualcho')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'Concepción')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'Dolores Merendón')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'Fraternidad')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'La Encarnación')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'La Labor')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'Lucerna')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'Mercedes')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'San Fernando')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'San Francisco del Valle')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'San Jorge')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'San Marcos')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'Santa Fe')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'Sensenti')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'Sinuapa')
GO

-- Olancho
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Juticalpa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Campamento')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Catacamas')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Concordia')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Dulce Nombre de Culmí')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'El Rosario')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Esquipulas del Norte')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Gualaco')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Guarizama')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Guata')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Guayape')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Jano')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'La Unión')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Mangulile')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Manto')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Salamá')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'San Esteban')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'San Francisco de Becerra')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'San Francisco de La Paz')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Santa María del Real')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Silca')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Yocón')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Patuca')
GO

-- Santa Bárbara
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Santa Bárbara')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Arada')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Atima')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Azacualpa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Ceguaca')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Concepción del Norte')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Concepción del Sur')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Chinda')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'El Níspero')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Gualala')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Ilama')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Las Vegas')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Macuelizo')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Naranjito')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Nueva Celilac')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Nuevo Celilac')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Petoa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Protección')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Quimistán')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'San Francisco de Ojuera')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'San José de Colinas')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'San Luis')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'San Marcos')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'San Nicolás')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'San Pedro Zacapa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'San Vicente Centenario')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Santa Rita')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Trinidad')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Las Flores')
GO

-- Valle
INSERT INTO Municipio (id_departamento, municipio) VALUES (17, 'Nacaome')
INSERT INTO Municipio (id_departamento, municipio) VALUES (17, 'Alianza')
INSERT INTO Municipio (id_departamento, municipio) VALUES (17, 'Amapala')
INSERT INTO Municipio (id_departamento, municipio) VALUES (17, 'Aramecina')
INSERT INTO Municipio (id_departamento, municipio) VALUES (17, 'Caridad')
INSERT INTO Municipio (id_departamento, municipio) VALUES (17, 'Goascorán')
INSERT INTO Municipio (id_departamento, municipio) VALUES (17, 'Langue')
INSERT INTO Municipio (id_departamento, municipio) VALUES (17, 'San Francisco de Coray')
INSERT INTO Municipio (id_departamento, municipio) VALUES (17, 'San Lorenzo')
GO

-- Yoro
INSERT INTO Municipio (id_departamento, municipio) VALUES (18, 'Yoro')
INSERT INTO Municipio (id_departamento, municipio) VALUES (18, 'Arenal')
INSERT INTO Municipio (id_departamento, municipio) VALUES (18, 'El Negrito')
INSERT INTO Municipio (id_departamento, municipio) VALUES (18, 'El Progreso')
INSERT INTO Municipio (id_departamento, municipio) VALUES (18, 'Jocón')
INSERT INTO Municipio (id_departamento, municipio) VALUES (18, 'Morazán')
INSERT INTO Municipio (id_departamento, municipio) VALUES (18, 'Olanchito')
INSERT INTO Municipio (id_departamento, municipio) VALUES (18, 'Santa Rita')
INSERT INTO Municipio (id_departamento, municipio) VALUES (18, 'Sulaco')
INSERT INTO Municipio (id_departamento, municipio) VALUES (18, 'Victoria')
INSERT INTO Municipio (id_departamento, municipio) VALUES (18, 'Yorito')
GO