INSERT INTO Departamento (nombre) VALUES ('Atlántida')
INSERT INTO Departamento (nombre) VALUES ('Choluteca')
INSERT INTO Departamento (nombre) VALUES ('Colón')
INSERT INTO Departamento (nombre) VALUES ('Comayagua')
INSERT INTO Departamento (nombre) VALUES ('Copán')
INSERT INTO Departamento (nombre) VALUES ('Cortés')
INSERT INTO Departamento (nombre) VALUES ('El Paraíso')
INSERT INTO Departamento (nombre) VALUES ('Francisco Morazán')
INSERT INTO Departamento (nombre) VALUES ('Gracias a Dios')
INSERT INTO Departamento (nombre) VALUES ('Intibucá')
INSERT INTO Departamento (nombre) VALUES ('Islas de la Bahía')
INSERT INTO Departamento (nombre) VALUES ('La Paz')
INSERT INTO Departamento (nombre) VALUES ('Lempira')
INSERT INTO Departamento (nombre) VALUES ('Ocotepeque')
INSERT INTO Departamento (nombre) VALUES ('Olancho')
INSERT INTO Departamento (nombre) VALUES ('Santa Bárbara')
INSERT INTO Departamento (nombre) VALUES ('Valle')
INSERT INTO Departamento (nombre) VALUES ('Yoro')
GO
select * from Departamento