INSERT INTO Municipio (id_departamento, municipio) VALUES (1, 'La Ceiba')
INSERT INTO Municipio (id_departamento, municipio) VALUES (1, 'Tela')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'Choluteca')
INSERT INTO Municipio (id_departamento, municipio) VALUES (2, 'San Marcos de Col�n')
INSERT INTO Municipio (id_departamento, municipio) VALUES (3, 'Trujillo')
INSERT INTO Municipio (id_departamento, municipio) VALUES (3, 'Tocoa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'Comayagua')
INSERT INTO Municipio (id_departamento, municipio) VALUES (4, 'Siguatepeque')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'Santa Rosa de Cop�n')
INSERT INTO Municipio (id_departamento, municipio) VALUES (5, 'La Entrada')
INSERT INTO Municipio (id_departamento, municipio) VALUES (6, 'San Pedro Sula')
INSERT INTO Municipio (id_departamento, municipio) VALUES (6, 'Puerto Cort�s')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Danl�')
INSERT INTO Municipio (id_departamento, municipio) VALUES (7, 'Yuscar�n')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Tegucigalpa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (8, 'Valle de �ngeles')
INSERT INTO Municipio (id_departamento, municipio) VALUES (9, 'Puerto Lempira')
INSERT INTO Municipio (id_departamento, municipio) VALUES (10, 'La Esperanza')
INSERT INTO Municipio (id_departamento, municipio) VALUES (11, 'Roat�n')
INSERT INTO Municipio (id_departamento, municipio) VALUES (12, 'La Paz')
INSERT INTO Municipio (id_departamento, municipio) VALUES (13, 'Gracias')
INSERT INTO Municipio (id_departamento, municipio) VALUES (14, 'Nueva Ocotepeque')
INSERT INTO Municipio (id_departamento, municipio) VALUES (15, 'Juticalpa')
INSERT INTO Municipio (id_departamento, municipio) VALUES (16, 'Santa B�rbara')
INSERT INTO Municipio (id_departamento, municipio) VALUES (17, 'Nacaome')
INSERT INTO Municipio (id_departamento, municipio) VALUES (18, 'Yoro')
GO