INSERT INTO Departamento (nombre) VALUES ('Atl�ntida')
INSERT INTO Departamento (nombre) VALUES ('Choluteca')
INSERT INTO Departamento (nombre) VALUES ('Col�n')
INSERT INTO Departamento (nombre) VALUES ('Comayagua')
INSERT INTO Departamento (nombre) VALUES ('Cop�n')
INSERT INTO Departamento (nombre) VALUES ('Cort�s')
INSERT INTO Departamento (nombre) VALUES ('El Para�so')
INSERT INTO Departamento (nombre) VALUES ('Francisco Moraz�n')
INSERT INTO Departamento (nombre) VALUES ('Gracias a Dios')
INSERT INTO Departamento (nombre) VALUES ('Intibuc�')
INSERT INTO Departamento (nombre) VALUES ('Islas de la Bah�a')
INSERT INTO Departamento (nombre) VALUES ('La Paz')
INSERT INTO Departamento (nombre) VALUES ('Lempira')
INSERT INTO Departamento (nombre) VALUES ('Ocotepeque')
INSERT INTO Departamento (nombre) VALUES ('Olancho')
INSERT INTO Departamento (nombre) VALUES ('Santa B�rbara')
INSERT INTO Departamento (nombre) VALUES ('Valle')
INSERT INTO Departamento (nombre) VALUES ('Yoro')
GO